### ISSUE TITLE
The new responsive design seems to miscalculate mobile screen width (still)

### ISSUE THREAD

**Issue by melikyuksel** [nutechsoftware/alarmdecoder-webapp#15]
I had accidentally opened this issue on the backend repo, right here: https://github.com/nutechsoftware/alarmdecoder/issues/7

Although it was closed as fixed in the latest release, the new version hasn't made a difference in how the interface looks; it looks identical to the old version and screenshot in the above issue link.

**Comment by weevis** [comment]
This has to do with the viewport settings I believe, I have added an iphone check to the ipad check and adjust the viewport for those devices to be 1.0 scale, hope that fixes it as it did on ipad.

line 40 of templates/layouts/base.html:

if( isiPad )

change to:

if( isiPad || isiPhone )


If you could test that since I don't have an iphone, that would be great.

**Comment by melikyuksel** [comment]
Thanks! It's almost there, the viewport is aligned thanks to your change, but the keypad buttons are still as tiny as before. The screen emulator is also way too big, and the "Armed" "Ready" "Chime" "Sounds:" items should be in one line but are getting split into two lines for no reason and pushing the keypad buttons too far down to be easily accessible. Screenshot:

![fullsizerender 12](https://cloud.githubusercontent.com/assets/10296053/22962484/03f23632-f31b-11e6-93d0-173d117190c9.jpg)

**Comment by weevis** [comment]
Huh, apparently bootstrap 3 detects iphone as an "xs" device, can you verify this for me?  Only surmising that because it seems the "col-xs-6" rules seem to be applying and stacking the icons 2x2.  It's intended as the template is written, I was just not aware that an iphone with a high density screen is detected as an 'xs' device - have no way to verify for myself.

**Comment by melikyuksel** [comment]
I'm not familiar with Bootstrap; do you know what I can do to see if it's detecting the iPhone as an 'xs' device?

**Comment by weevis** [comment]
I'm hoping this codepen will tell you http://codepen.io/dih/full/ivECj

**Comment by melikyuksel** [comment]
Thanks, that page says that the iPhone (6) is XS.

**Comment by weevis** [comment]
Well that explains a lot as far as the layout goes... It's doing exactly what the template says to do for 'xs' devices ... hope to have something useful next week.  Thanks for the help.

**Comment by weevis** [comment]
[test_layout.zip](https://github.com/nutechsoftware/alarmdecoder-webapp/files/798053/test_layout.zip)

If you can upload these files to your pi in the ad2web directory and try an updated new layout for the ademco keypad that would help me out a lot.

**Comment by weevis** [comment]
Any word on this new layout fixing your usability issues?

**Comment by melikyuksel** [comment]
@weevis Hey there, sorry about the long delay. I had a chance to test out the new layouts, and it seems to be quite a lot better on an iPhone now. Screenshot attached. The buttons are still a bit smaller than ideal (they would probably be better off if they weren't so thin and wide, but more square-like). The screen emulator looks great!

![fullsizerender 13](https://cloud.githubusercontent.com/assets/10296053/23584143/1683e5ca-0126-11e7-8ead-b084eccf9f94.jpg)

**Comment by weevis** [comment]
I will see what I can do about button size, but with the image assets we use this might be what it ends up being.
