### ISSUE TITLE
Notification event "relay has been changed" not working

### ISSUE THREAD

**Issue by digiblur** [nutechsoftware/alarmdecoder-webapp#27]
I can see !REL messages coming across the port 10000 telnet port but the notifications are not firing when the relay has changed.  

Also, it seems like this notification should be expanded to allow the user to select the relay number and state of the relay to really make this feature functional.

**Comment by endlesscoil** [comment]
I have a partial resolution to this that I'll try and push up this weekend.  It wires up the event properly and provides address/channel/status information in the message.  I'll need someone to test, though, as I don't have a working relay setup.  We can see about adding the filtering after we confirm it functions properly.

**Comment by digiblur** [comment]
Nice! I have one relay output setup and I can definitely test anything needed. I can setup a few more though to test as I would like to utilize the HTTP call out to a local address based on the relay triggered.

**Comment by f34rdotcom** [comment]
I can test in my lab and at home.

**Comment by endlesscoil** [comment]
Okay, this is pushed up into master.  Sorry that took so long.

**Comment by digiblur** [comment]
Doesn't seem to be working here.  I tried the notification again with on relay changed and did a test, the test email sends but nothing sends when a relay is triggered.  I can see the relay messages coming across port 10000, plus I threw together a piece of code in Python using the alarmdecoder library to update a topic in MQTT when the relay is triggered and it triggers fine on the on_relay_changed callback.  

Ultimately that would be an awesome feature to dump the various states and such to MQTT for universal support with several applications.  Might have to do some digging through the code to see how tough it would be next weekend.

**Comment by endlesscoil** [comment]
Hm, maybe Sean can help debug a bit.  I won't have a working dev
environment for a while.

Sounds like you have a cool setup going; look forward to seeing what you
come up with.

**Comment by f34rdotcom** [comment]
Ok it is fixed in dev. I have not pushed it up yet but will this weekend. 
I added the relay event messages to my UPNPPush notifications.

I am seeing the same issues I have with the LRR messages. The format I picked was "{message}". This gave me the raw LRR message `<eventmessage><![CDATA[!LRR:001,1,CID_1441,ff]]></eventmessage>`

As soon as someone changes the format it will break the receiver of the event.

I would like to work on a patch that exposes the **RAW** event message. For the RELAY event as you can see it has the old event format but even if I updated it I do not think it helps the person who has to write code to take actions based upon the event. IMHO it needs to stay the AlarmDecoder protocol.

For things like EMail notification it is smart to reformat the data to be more human readable. I think for other event handlers it would be best to not touch the message and send it raw. 

In any case the way it is written now its not even possible to get the raw message as it is never send to the event handlers. This is what I would like to change next. Then we can add "RAW" checkbox options on notification setup pages.

Ultimately getting rid of <panelstate/> or making it optional would be a good long term goal leaving "reload()" to pull the current state to deal with any sync issues when messages are lost. This would reduce the size of the data transferred and be more efficient.

```
<e:propertyset xmlns:e="urn:schemas-upnp-org:service:AlarmDecoder:1">
  <e:property>
    <eventid>12</eventid>
    <eventdesc>relay changed</eventdesc>
    <eventmessage><![CDATA[A relay has changed.]]></eventmessage>
  </e:property>
  <e:property>
    <panelstate><panel_armed_stay>False</panel_armed_stay><panel_type>ADEMCO</panel_type><panel_bypassed>{}</panel_bypassed><panel_ready>True</panel_ready><panel_alarming>False</panel_alarming><panel_on_battery>True</panel_on_battery><panel_fire_detected>False</panel_fire_detected><panel_powered>True</panel_powered><panel_panicked>False</panel_panicked><panel_armed>False</panel_armed><panel_relay_status><r><a>12</a><c>2</c><v>0</v></r><r><a>12</a><c>4</c><v>0</v></r><r><a>12</a><c>1</c><v>0</v></r><r><a>12</a><c>3</c><v>0</v></r></panel_relay_status><panel_zones_faulted /><last_message_received><!-- --><![CDATA[[10000001000100003A0-],008,[f70000040008005c08020000000000],"****DISARMED****  Ready to Arm  "]]><!-- --></last_message_received></panelstate>
  </e:property>
</e:propertyset>

```

**Comment by f34rdotcom** [comment]
Please tests and I will close.

**Comment by f34rdotcom** [comment]
Works. I only selected RELAY change event. What options do you have selected?

```
A relay at 12:2 has changed to CLOSED.

Message sent at Mon Apr 23 04:12:49 2018.
```

**Comment by digiblur** [comment]
Hmm...I'll delete the notification and recreate, I believe I just went default on everything except putting the check mark on relay changed box.

**Comment by f34rdotcom** [comment]
cd /opt/alarmdecoder
sudo python setup.py install

Then restart pi or gunicorn service.

The api is not being updated fully. Bug :(

Best
SM

**Comment by digiblur** [comment]
Ahh...gotcha.  That fixed it.  Run the command in docker container and restarted the container.  All good now.  Much appreciated!

**Comment by f34rdotcom** [comment]
All working well in latest releases. Closing.
