### ISSUE TITLE
Blocks and causes gunicorn to restart.

### ISSUE THREAD

**Issue by f34rdotcom** [nutechsoftware/alarmdecoder-webapp#32]
https://github.com/nutechsoftware/alarmdecoder-webapp/blob/0b754de5a7bfd966a57ade447a30c2e2bd3e87b6/ad2web/upnp.py#L66

If a system exists on the same network with a different subnet it will respond with a UPNP UDP request with a url on the incorrect subnet. the call to selectigd() will stall out trying to complete this HTTP request. I can find no info on the upnp library in regards to a timeout that addresses this issue. I did see someone supply a patch a long time ago to add timeouts to selectigd() but it looks to have stalled.

What is the best way to call this and not block? or to wrap it with a timeout alarm to kill call and prevent the restart and blocking that can take afaik minutes.

**Comment by endlesscoil** [comment]
Stopping a thread in Python is sketchy at best.  That's why the _running flag is used and if it's blocked that's going to be a bit of an issue.

As far as I remember subprocesses can be killed more easily, so you might consider converting it and then keeping a timestamp that the subprocess updates.  

If it hasn't been updated in however long, kill the process and relaunch.  Just remember that it does have a 3 hour sleep in it.  Would be a good chance to eliminate that, too.

**Comment by f34rdotcom** [comment]
In theory this issue is better now. I still need to look over the UPNP thread but at least notifications are now non blocking.
