### ISSUE TITLE
Services might still be starting after trying to update the webapp

### ISSUE THREAD

**Issue by jonathankochel** [nutechsoftware/alarmdecoder-webapp#48]
Ran the web update for the alarmdecoder-webapp through the browser.  Ran for several hours and nothing was happening so I rebooted.  Now when I try to load the page I get "Services might still be starting"

**Comment by digiblur** [comment]
I've had this issue the other day due to an incorrect shutdown.  Mine is running the docker so I bash'd into the docker container and ran the following (which was found on the forums).  Restarted and worked like a charm.  

cd /opt/alarmdecoder
git pull origin master
sudo python setup.py install
cd ../alarmdecoder-webapp
git pull origin master

I exited the container and did a container restart or you can do a proper shutdown as well.

**Comment by jonathankochel** [comment]
This fixed the issue. Thank you!

I am not sure if it mattered but I did a 
sudo python setup.py install
In the webapp directory also.

**Comment by digiblur** [comment]
Glad you got it going!  Thanks for the follow-up.

**Comment by Segfaul198** [comment]
Holy crap! Thank you for this. Been having this problem for ages. Thought it was related to the Flask issue but this seems to have sorted it. Thanks again!

**Comment by mattolden** [comment]
I tried the same steps to no avail.  Rebooted system, still getting "Services might still be starting - please wait and try again." 502 Bad Gateway error when trying to get to webapp.

**Comment by mattolden** [comment]
Bizarre. The only recovery I found was to reimage the SD card and start from scratch. Had it running for 2 days and was attempting to add some cameras to it when 504 Gateway Timeout errors after adding first camera.  Retried the above steps by digiblur and now I get 502 Bad Gateway.

**Comment by f34rdotcom** [comment]
Ok warning on update screen about backups and recovery.
